# Generated by Django 3.0.1 on 2020-08-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Confirm_Password', models.CharField(max_length=50)),
                ('Company_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('post_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Tender_Image', models.ImageField(default='img.jpg', upload_to='')),
                ('Tender_Name', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Tender_Type', models.CharField(max_length=50)),
                ('Business_Scale', models.CharField(max_length=50)),
                ('Entry_Fee', models.IntegerField()),
                ('Rules_Regulation', models.CharField(max_length=500)),
                ('uses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tender.USER')),
            ],
            options={
                'db_table': 'post_data',
            },
        ),
    ]
