# Generated by Django 3.0.1 on 2020-08-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPLY',
            fields=[
                ('apply_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('Company_Name', models.CharField(max_length=50)),
                ('Phone_no', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('CV_file', models.FileField(default='cv.doc', upload_to='')),
                ('post_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tender.POST')),
                ('uses_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tender.USER')),
            ],
            options={
                'db_table': 'apply_data',
            },
        ),
    ]
