# Generated by Django 3.0.1 on 2020-08-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0002_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uses_id',
        ),
    ]
