# Generated by Django 3.0.1 on 2020-09-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0004_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='uses_id',
            new_name='uses',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
