# Generated by Django 3.0.1 on 2020-09-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0005_auto_20200903_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='uses',
            new_name='user',
        ),
    ]
