# Generated by Django 3.0.1 on 2020-09-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0006_auto_20200903_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='apply_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
