# Generated by Django 3.0.1 on 2020-09-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0007_auto_20200904_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
