# Generated by Django 3.0.1 on 2020-09-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0008_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to=''),
        ),
    ]
