# Generated by Django 3.0.1 on 2020-09-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0009_auto_20200906_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='img.jpg', null=True, upload_to=''),
        ),
    ]
