# Generated by Django 3.0.1 on 2020-09-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0010_auto_20200906_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
