# Generated by Django 3.0.1 on 2020-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0012_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
