# Generated by Django 3.0.1 on 2020-09-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0013_auto_20200906_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to=''),
        ),
    ]
