# Generated by Django 3.0.1 on 2020-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0016_auto_20200906_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Tender_Image',
            field=models.ImageField(upload_to='Tender'),
        ),
    ]
