# Generated by Django 3.0.1 on 2020-09-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0017_auto_20200906_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='CV_file',
            field=models.FileField(upload_to='cv.doc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='Profile'),
        ),
    ]
