# Generated by Django 3.0.1 on 2020-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tender', '0018_auto_20200906_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='CV_file',
            field=models.FileField(default='cv.doc', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='Tender_Image',
            field=models.ImageField(default='Tender.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='Profile.jpg', upload_to=''),
        ),
    ]
